### ISSUE TITLE
Using PSU and Shelly Plug in, switch off on boot

### ISSUE THREAD

**Issue by michaestraub** [edekeijzer/OctoPrint-PSUControl-Shelly#10]
What is the problem?
Using PSU and Shelly Plug in, switch off on boot. I Use a Shelly PlugS.

What did you already try to solve it?
After about 20 sec switch socket on and rasperry is connecting, my shelly will switched off by PSU. When I dispale the Hook at Power Off Option it will persist, any help on that?

Does anybody have an Idea how to solve?

At least, I wont printer switched of after finnishing.

Thanks Michael

Plese find detailed information int that thread:
https://community.octoprint.org/t/using-psu-and-shelly-plug-in-switch-off-on-boot/41234

**Comment by edekeijzer** [comment]
@michaestraub what exactly do you mean by switch off on boot? It will switch off your Shelly when Octoprint is starting? I have just tried to replicate this by linking a Plug S to my Octoprint test environment (Docker) but I am unable to replicate.
Could you show all settings of PSUControl and PSUControl-Shelly? Also, could you set the log level for *octoprint.plugins.psucontrol_shelly* to **DEBUG** and attach the octoprint.log to this issue?
