### ISSUE TITLE
Multiple Shelly Plugs?

### ISSUE THREAD

**Issue by acer8888** [edekeijzer/OctoPrint-PSUControl-Shelly#12]
Hello, I was wondering if there is a way to use multiple shelly plugs with this plugin?

For instance, I have one plug for my mainboard, and a second for my AC heated bed. 

Thank you!

**Comment by edekeijzer** [comment]
This is not possible (at least not by me) since this plugin is just a connector between [PSUControl](https://github.com/kantlivelong/OctoPrint-PSUControl) and Shelly. If possible, it should be done there.
