### ISSUE TITLE
[FEATURE REQUEST] Multiple IDs for more Shellys.

### ISSUE THREAD

**Issue by DivineJimmi** [edekeijzer/OctoPrint-PSUControl-Shelly#13]
I am using a Shelly 2.5.
One Output for my printer and the other one for my Palette 3 Pro and some heated Filament boxes.
Currently i am only able to control my printer with one ID. But i need to be able to switch two IDs on and off for printing.

Would be nice if i could switch both with different Marlin-Codes. Like Output 0 with M4 and Output 1 with M5. Or something like that.

**Comment by edekeijzer** [comment]
While this sounds as a nice idea, I'm afraid it is harder than you'd think. This plugin is just an interface between the main PSUControl and the Shelly API, the switching on GCODE is in the main plugin so it would need an update over there.
Secondly, the power switch in Octoprint has a state, which reflects the state of the Shelly. What should the plugin display if one is on and the other is off? Or one of them becomes unavailable? I think you should be able to achieve this through Shelly scripts.
