### ISSUE TITLE
Shelly Plug S can't be controlled.

### ISSUE THREAD

**Issue by Mikyner** [edekeijzer/OctoPrint-PSUControl-Shelly#18]
I use Shelly Plug S. Octoprint can see its status, but it cannot be controlled.

![image](https://user-images.githubusercontent.com/52259575/214840729-61e284b0-355e-4411-88c4-da5fd40dc9f2.png)

**Comment by edekeijzer** [comment]
I am pretty sure it can, because I used a Plug S for testing when creating this plugin. Did you set the Shelly plugin as both switching and sensing plugin in PSUControl? If so, please add debug logging.

**Comment by Mikyner** [comment]
I'll attach the debug logs in about an hour, I'm printing right now.

**Comment by edekeijzer** [comment]
> I'll attach the debug logs in about an hour, I'm printing right now.

Not necessary, set the Switching Method to Plugin/Shelly and I'm sure it will work.
