### ISSUE TITLE
Shelly Plug S only switching after reboot

### ISSUE THREAD

**Issue by gimpfenlord** [edekeijzer/OctoPrint-PSUControl-Shelly#8]
My plugin is configured correctly.
API Key is set

the log says:
2021-12-03 13:55:35,017 - octoprint.plugins.psucontrol - INFO - Switching PSU On
2021-12-03 13:55:35,172 - octoprint.plugins.psucontrol_shelly - WARNING - Server returned 401 Unauthorized. Check username/password or API key.

after a reboot of my octopi it works again -_-

**Comment by ManuMCoupe** [comment]
Same issue here with Shelly S :-S

**Comment by gimpfenlord** [comment]
after changing from cloud to local ip it seems to work now
so the problem may be the cloud connection

**Comment by ManuMCoupe** [comment]
> after changing from cloud to local ip it seems to work now so the problem could be the cloud connection

I didn't put PSU Control/Plugin on Sensing... Know, it seems to work into cloud mode... But the android app of Shelly don't update automatically. But it works!

**Comment by edekeijzer** [comment]
@gimpfenlord sorry for the slow response. Did you see the above comment? Is your sensing method set to the right plugin?
